[package]
name = "financial_data_fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.9.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
